### ISSUE TITLE
Allow Resque 2.1.0

### ISSUE THREAD

**Issue by peret** [stulentsev/resque-multi-job-forks#24]
Hello,

a new version 2.1.0 of the resque gem was just released: https://github.com/resque/resque/releases/tag/2.1.0
resque-multi-job-forks is currently preventing me from updating, would it be possible to include this version in the version range? 🙏

**Comment by stulentsev** [comment]
I'd be happy to, but it requires some work to verify that this code still works on 2.1 and fix it if it doesn't. While I'm trying to find the time, could you maybe give it a shot?

**Comment by peret** [comment]
Hey,

I'd be happy to! I tested it locally already with one of our workers, and everything still works as expected, i.e. the child process works on multiple jobs before forking again:
<img width="315" alt="PlaytestCloud_—_docker-compose_run_runner-dev__bin_bash_—_com_docker_cli_◂_docker-compose_run_runner-dev__bin_bash_—_202×55" src="https://user-images.githubusercontent.com/617977/129734035-c138ae68-f524-4390-8d8c-3b53843e38ec.png">

I also had a look at the changes made in the resque gem, especially `Resque::Worker` and none of them look like they would interfere with the operation of resque-multi-job-forks. I'm not an expert on how this gem works, so maybe I'm missing something non-obvious, but it looks good to me.

Is there anything else you want to have tested specifically?

**Comment by stulentsev** [comment]
@peret pushed 0.5.3. Thank you for raising this!
